# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b8217b323b51917071e1e7e3c4f54efe72dff39aebc2d99edfba9648445b281f22b07ee92e304bee08b6420c42c79418656630b6eef62320610ac93e9b1f4ba

test:
  secret_key_base: 2f47e0477be726aeaf410c4bb3c52a57ff42ff9ba71e44899905564a1ac5943ef43906551e21fa3e5d681c4a09a99ce9ade00c4230dbaca8d8d0679f2988fc84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
